backend:
  name: git-gateway

media_folder: "img" # Folder where user uploaded files should go
display_url: https://studioplietsch.netlify.com

collections: # A list of collections the CMS should be able to edit
  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    preview_template: blog
    folder: "collections/_projects" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "test", name: "title", widget: "string", tagname: "h2"}
      - label: "Address"
        name: "address"
        widget: "object"
        fields: 
          - {label: "Street Address", name: "street", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "Postal Code", name: "post-code", widget: "string"}

    meta: # Meta data fields. Just like fields, but without any preview element

