company-title: STUDIO Plietsch
description: Büro für Innenarchitektur
address:
  city: Hamburg
  post-code: '20144'
  street: Schlankreye 38
phone: +49 40 319 77 919
email: info@studioplietsch.de
web: www.studioplietsch.de
tax-number: 42/275/04051
