company-title: STUDIO Plietsch
description: Büro für Innenarchitektur
address:
  city: Hamburg
  post-code: '20144 '
  street: Schlankreye 38
phone: 040 319 77 919
email: info@studioplietsch.de
web: www.studioplietsch.de
