backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "src/img" # Folder where user uploaded files should go
public_folder: "img"
display_url: https://studioplietsch.netlify.com

collections: # A list of collections the CMS should be able to edit
  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI, ie.: "New Post"
    folder: "src/collections/_projects" # The path to the folder where the documents are stored
    sort: "title:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields: 
          - label: "Images"
            name: "images"
            widget: "list"
            fields: 
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Alternative Text", name: "alt", widget: "string"}
          - {label: "Text", name: "text", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Title", name: "title", widget: "string", tagname: "h2"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Alt Text", name: "alt", widget: "string"}
          - {label: "Contact", name: "contact", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/index.md"
        label: "Studio"
        name: "studio"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string", tagname: "h2"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Alt Text", name: "alt", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
